### ISSUE TITLE
WIP vs Draft

### ISSUE THREAD

**Issue by zeke** [amannn/action-semantic-pull-request#21]
Hey @amannn I noticed there's a new feature to support a [WIP] prefix: https://github.com/amannn/action-semantic-pull-request/pull/3

Did you consider GitHub's [draft pull requests](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests) feature? Instead of using that WIP prefix, this Action could check whether or not the PR is a draft and react accordingly.

**Comment by amannn** [comment]
Hi @zeke,

yep, that's true. I added the WIP support because it seems like Github has disabled the draft pull request feature for private projects on the free plan.

But for "real" draft pull requests, wouldn't it make sense anyway to already validate the title and to expect the prefixes? Similar to how you also want e.g. your tests to run and potentially fail, even if you don't intend to merge the PR just yet.

For the `[WIP]` PRs in practice I still use titles like `[WIP] feat: Add button` and already indicate the release type.

What do you think?
