### ISSUE TITLE
Support `merge_group` event

### ISSUE THREAD

**Issue by Erazihel** [amannn/action-semantic-pull-request#236]
GitHub recently released the [merge queue feature](https://github.blog/2023-07-12-github-merge-queue-is-generally-available/).

In order to use it, we need to trigger checks using a new event: `merge_group`. More details [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions).

Unfortunately, this GitHub Action is only working for the `pull_request_target` and `pull_request` events at the moment as mentioned in documentation.

This means that we can't check for a PR title using the merge queue as you can see:

<img width="1068" alt="image" src="https://github.com/amannn/action-semantic-pull-request/assets/3669588/9b83952e-37cb-4833-916b-7db0d5eb6bde">

Is adding the `merge_group` event something feasible to this GitHub Action?

Thanks!

**Comment by amannn** [comment]
Hmm, I'm wondering if this action is something you'd want to run in a merge queue in the first place? Do you have experience with merge queues? Can the pull request title be changed while the pull request is in the queue? Otherwise my impression would be that you only want to validate the PR title when the PR itself is updated (not when it's added to a merge queue).

![image](https://github.com/amannn/action-semantic-pull-request/assets/4038316/c6aa48bb-20a8-408b-b5c4-900e5e8e268b)

The error you're seeing originates from here:

https://github.com/amannn/action-semantic-pull-request/blob/00282d63cda40a6eaf3e9d0cbb1ac4384de896e8/src/index.js#L28-L33

We need to access the pull request that is related to the trigger of the action. Do you know if there's a way to achieve this for merge queues? If there's an easy fix that doesn't have any downside, I'd definitely be open to supporting this in case you'd be interested in contributing this feature!

**Comment by Erazihel** [comment]
> I'm wondering if this action is something you'd want to run in a merge queue in the first place?

Technically no but unfortunately for now you can't have different required checks for the `pull_request` and `merge_group` events in GitHub.

That means that if I want to require the validation of the title of my PR, it'll be required for the `pull_request` event but also when the `merge_group` event will run the checks.

But since we can't run this GitHub Action for the `merge_group` event, the check never runs and the PR is never merged.

For now I had to make this check not required to make it work.

> Do you have experience with merge queues?

I must admit that this pretty new to me so no.

> Can the pull request title be changed while the pull request is in the queue?

That's a really nice question! I just tried it and yes, the title can be changed while the PR is in queue.

> We need to access the pull request that is related to the trigger of the action. Do you know if there's a way to achieve this for merge queues?

Based on the [documentation](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#merge_group), I fear that we won't be able to get the PR context 😕 

I'll try to dive deeper in the subject but I don't think there is any solution possible there 😔

**Comment by gdarchen** [comment]
Hey there!

I just face exactly the same issue.
The PR title lint action is required in our branch protection for `master` but it is never fired for PRs added in the merge queue.

I tried adding the `merge_group:` event in the action and add the mentioned error message:
```
This action can only be invoked in `pull_request_target` or `pull_request` events. Otherwise the pull request can't be inferred.
```

Do you think it's possible to support the `merge_group` event? 🙏
