### ISSUE TITLE
 Prototype-polluting function / argument

### ISSUE THREAD

**Issue by EelcoLos** [amannn/action-semantic-pull-request#252]
**Describe the bug**

Github security on our fork is reporting these 2 types of alerts on code scanning. However, they are on generated code (on the `dist/index.js` file)

> Most JavaScript objects inherit the properties of the built-in Object.prototype object. Prototype pollution is a type of vulnerability in which an attacker is able to modify Object.prototype. Since most objects inherit from the compromised Object.prototype, the attacker can use this to tamper with the application logic, and often escalate to remote code execution or cross-site scripting.

**To reproduce**

run the github scanning on the repository

**Expected behavior**

I'm not entirely sure whether this code is generated by github or something that is generated part of the source. Therefore it's not easy to determine whether to dismiss this as a false positive or not.

**Comment by amannn** [comment]
`dist/index.js` is compiled statically as part of every build of this action and can not be modified by developers when using the action. I'm unsure how anyone (including developers) would be able to change the object prototype in a harmful way.

Note that this action depends on 3rd party libraries:

https://github.com/amannn/action-semantic-pull-request/blob/67cbd7a15a6eeea0c3a0dffff4768fa5653de05c/package.json#L25-L31

Not sure if the warning you're seeing is caused by 1st or 3rd party code.
